name: Mobile-Mac-VPS
on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Setup Password
        run: |
          sudo sysadminctl -adminUser runner -adminPassword "" -password "1111"
          
      - name: Install Tailscale via Brew
        run: |
          # Brew sabse reliable hai Mac par
          brew install tailscale
          
      - name: Start Tailscale Service
        run: |
          # Service start karke login karna
          sudo tailscaled --tun=userspace-networking &
          sleep 10
          # Nayi key yahan dalein ya secret use karein
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_KEY }} --hostname=mac-vps
          
      - name: Enable Screen Sharing
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -restart -agent -privs -all
          echo "Mac VPS Active! Check Tailscale Dashboard for IP."
          
      - name: Keep Alive
        run: sleep 21600
