name: Mobile-Mac-VPS
on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Setup User Password
        run: |
          # System user 'runner' ka password set karna
          sudo sysadminctl -adminUser runner -adminPassword "" -password "1111"
          
      - name: Install Tailscale via Brew
        run: |
          brew install tailscale
          
      - name: Start Tailscale
        run: |
          sudo tailscaled --tun=userspace-networking &
          sleep 10
          # Nayi reusable key secret mein lazmi update karein
          sudo tailscale up --authkey=tskey-auth-kMH4hKgqVY11CNTRL-guT4SrPpK2aoRrxjCWRt1aMZYMREkinc --hostname=mac-vps
          
      - name: Configure VNC (No Auth Error)
        run: |
          # Remote Management activate karna
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -restart -agent -privs -all
          
          # VNC Legacy Password '1111' set karna (Authentication fix)
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvnclegacy -vnclegacy yes
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvncpw -vncpw 1111
          
          # Settings apply karne ke liye restart
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -restart -agent
          echo "VPS is ready! Password is 1111"
          
      - name: Keep Alive
        run: sleep 21600
        
